{
    "runtime": "python",
    "version": "0.1.37",
    "trace": {
        "name": "run",
        "__time": {
            "start": "2024-11-27T07:23:19.591078",
            "end": "2024-11-27T07:23:19.608566",
            "duration": 17
        },
        "signature": "__main__.SceneDescriptionAssistant.run",
        "inputs": {
            "question": [
                "a man in a white shirt",
                "a close up of a person's face with glasses",
                "a green scope with a helicopter in the background",
                "a black and gold logo",
                "a close up of a pair of glasses",
                "a close up of a person's lips",
                "a man in a white shirt",
                "a close-up of a man's face",
                "a close up of a person's face"
            ]
        },
        "__frames": [
            {
                "name": "execute",
                "__time": {
                    "start": "2024-11-27T07:23:19.591078",
                    "end": "2024-11-27T07:23:19.591604",
                    "duration": 0
                },
                "signature": "prompty.execute",
                "description": "Execute a prompty"
            }
        ],
        "result": {
            "exception": {
                "type": "<class 'TypeError'>",
                "traceback": [
                    "  File \"C:\\Users\\whaak\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\prompty\\tracer.py\", line 149, in wrapper\n    result = func(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^\n",
                    "  File \"C:\\Users\\whaak\\OneDrive\\Code\\ai-examples\\imagecaption-web\\imagecaption.py\", line 104, in run\n    result = prompty.execute(\n             ^^^^^^^^^^^^^^^^\n",
                    "  File \"C:\\Users\\whaak\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\prompty\\tracer.py\", line 145, in wrapper\n    inputs = _inputs(func, args, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                    "  File \"C:\\Users\\whaak\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\prompty\\tracer.py\", line 118, in _inputs\n    ba = inspect.signature(func).bind(*args, **kwargs)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
                    "  File \"C:\\Users\\whaak\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 3259, in bind\n    return self._bind(args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
                    "  File \"C:\\Users\\whaak\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 3248, in _bind\n    raise TypeError(\n"
                ],
                "message": "got an unexpected keyword argument 'api_key'",
                "args": "(\"got an unexpected keyword argument 'api_key'\",)"
            }
        }
    }
}